// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAittrcg_aDs1ychZY-FnKGkJct0Rbz5xc',
    appId: '1:845186432759:web:3a794fc5e5c742963addf2',
    messagingSenderId: '845186432759',
    projectId: 'fir-21312040-b2976',
    authDomain: 'fir-21312040-b2976.firebaseapp.com',
    storageBucket: 'fir-21312040-b2976.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8J7uBQ2t3an3utKuaghvsydKgpD5Whk',
    appId: '1:845186432759:android:9370d1d921e09aeb3addf2',
    messagingSenderId: '845186432759',
    projectId: 'fir-21312040-b2976',
    storageBucket: 'fir-21312040-b2976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMMP1us_Q9X2hJ_3GoHKL_v6f6enAaSNg',
    appId: '1:845186432759:ios:fc75de0927f489503addf2',
    messagingSenderId: '845186432759',
    projectId: 'fir-21312040-b2976',
    storageBucket: 'fir-21312040-b2976.appspot.com',
    iosClientId: '845186432759-em0ihqtidfaoko4pq037k89kr8d4hgm6.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMMP1us_Q9X2hJ_3GoHKL_v6f6enAaSNg',
    appId: '1:845186432759:ios:fc75de0927f489503addf2',
    messagingSenderId: '845186432759',
    projectId: 'fir-21312040-b2976',
    storageBucket: 'fir-21312040-b2976.appspot.com',
    iosClientId: '845186432759-em0ihqtidfaoko4pq037k89kr8d4hgm6.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );
}
